kind: Secret
apiVersion: v1
metadata:
  name: {{ include "test-cd.fullname" . }}
  annotations:
    avp.kubernetes.io/path: "secret/webapp/config"
type: Opaque
data:
  username: <username>
  password: <password>