kind: Secret
apiVersion: v1
metadata:
  name: {{ include "test-cd.fullname" . }}
  annotations:
    avp.kubernetes.io/path: "secret/data/webapp/config"
type: Opaque
data:
  testb64: <testb64>
  username: <path:secret/webapp/config#username | base64encode>