kind: Secret
apiVersion: v1
metadata:
  name: {{ include "test-cd.fullname" . }}
type: Opaque
data:
  # test 555666777
  testb64: {{ .Values.vault.hostname }}
  username: {{ .Values.vault.username }}
  password: {{ .Values.vault.password }}